name: Release to NPM

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/${{github.repository}}:master
    steps:
      - name: make publish
        run: |
          if [ "$NODE_AUTH_TOKEN" ]; then
            export NODE_AUTH_TOKEN=`echo $NODE_AUTH_TOKEN | sed 's/ *$//g'`
          else
            echo "NODE_AUTH_TOKEN is not set"
            exit 1
          fi
          cd /opt/webr/src && make publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
