name: Release to NPM

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/${{github.repository}}:master
    steps:
      - name: make publish
        run: |
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "NODE_AUTH_TOKEN is not set"
            exit 1
          fi
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          cd /opt/webr/src && make publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
